#!/bin/sh
set -euf

## Program Tracking

program_command="curl-chatgpt"
program_version="1.0.0"
program_updated="2023-03-13T05:55:35Z"
program_license="MIT or Apache-2 or GPL-2.0 or GPL-3.0 or contact us for more"
program_website="https://github.com/sixarm/curl-chatgpt"
program_contact="Joel Parker Henderson (joel@sixarm.com)"

## Help Function

help(){
cat << EOF
curl-chatgpt

Curl shell script to connect to the OpenAI ChatGPT API,
and print the result's choice's message content as text.

Syntax:

    curl-chatgpt <prompt-content>

    curl-chatgpt --output <output-file> <prompt-content>

    curl-chatgpt --input <input-file>

    curl-chatgpt --input <input-file> --output <output-file>

Examples:

    curl-chatgpt "What is the meaning of life?"

    curl-chatgpt --output result.txt "What is the meaning of life?"

    curl-chatgpt --input prompt.txt

    curl-chatgpt --input prompt.txt --output result.txt

## Setup

To use this program, you need to first do this:

  1. Get your own OpenAI ChatGPT API key from
     https://platform.openai.com/account/api-keys

  2. Export the key into your local environment:
     export OPENAI_API_KEY=<KEY>

## Options

  * -h --help: 
      print helpful information

  * -v --verbose: 
      print diagnostic information; use twice for more information

  * -V --version: 
      print the program version number

  * -i --input <file>:
      input the request content text from an exiting file

  * -o --output <file>:
      output the response content text into a new file

  * -c --content <text>:
      explicitly provide a request content prompt string

  * --program-command:
      print the program command name

  * --program-version:
      print the program version number

  * --program-updated:
      print the program updated date

  * --program-license:
      print the program license name

  * --program-website:
      print the program website URL

  * --program-contact:
      print the program contact information for the maintainer

  * --program-website:
      print the program website URL

## Repetition

The options for --input, --output, and --content may be repeated.

Examples:

    curl-chatgpt "prompt 1" "prompt 2" "prompt 3"

    curl-chatgpt -i in1.txt -o out1.txt -i in2.txt -o out2.txt

## Tracking

  * Command: $program_command
  * Version: $program_version
  * Updated: $program_updated
  * License: $program_license
  * Website: $program_website
  * Contact: $program_contact
  
EOF
}

## 
# SixArm unix shell functions:
# https://github.com/sixarm/sixarm-unix-shell-functions
##

# Exit code: OK i.e the program run is a success.
EX_OK=0

# Exit code: a service is unavailable. This can occur if a support program or
# file does not exist. This can also be used as a catchall message when
# something you wanted to do does not work, but you do not know why.
EX_UNAVAILABLE=69

# out: print output message to stdout.
#
# Example:
# ```
# out "my message"
# => my message
# ```
#
# We use `printf` instead of `echo` because `printf` is more consistent
# on more systems, such a for escape sequence handling.
#
# Compare:
#
#   * Use the `out` function to print to STDOUT.
#
#   * Use the `err` function to print to STDERR.
#
out() {
        printf %s\\n "$*"
}

# die: print error message to stderr, then exit with error code.
#
# Example:
# ```
# die 1 "my message"
# STDERR=> my message
# => exit 1
# ```
die() {
        n="$1" ; shift ; >&2 printf %s\\n "$*" ; exit "$n"
}

# cmd: return true iff a command exists.
#
# Example:
# ```
# cmd grep
# => true
#
# cmd curl
# => false
# ```
cmd() {
        command -v "$1" >/dev/null 2>&1
}

# cmd_or_die: ensure a command exists.
#
# Example:
# ```
# cmd_or_die grep
# => true
#
# cmd_or_die curl
# STDERR=> Command needed: curl
# => exit 1
# ```
cmd_or_die() {
        cmd "$1" || die "$EX_UNAVAILABLE" "Command needed: $1"
}

##
# Core
##

curl_cmd() {
    case $verbose in
        0|1)
            printf %s "curl --silent"
            ;;
        2)
            printf %s "curl"
            ;;
        *)
            printf %s "curl --verbose"
            ;;
    esac
}

curl_chatgpt() {
    curl=$(curl_cmd)
    if [ $verbose -ge 2 ]; then set -x; fi
    $curl "https://api.openai.com/v1/chat/completions" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "Content-Type: application/json" \
    -d "{
    \"model\": \"gpt-3.5-turbo\",
    \"messages\": [{\"role\": \"user\", \"content\": \"$1\"}] 
    }" | 
    jq -r '.choices[0].message.content'
    if [ $verbose -ge 2 ]; then set +x; fi
}

curl_chatgpt_wrapper() {
    content="$1"
    if [ $verbose -gt 0 ]; then
        msg="curl_chatgpt"
        if [ -n "${input+1}" ]; then
            msg="$msg --input \"$input\""
        fi
        if [ -n "${output+1}" ]; then
            msg="$msg --output \"$output\""
        fi
        out "$msg \"$content\""
    fi
    if [ -n "${output+1}" ]; then
        curl_chatgpt "$content" > "$output"
    else 
        curl_chatgpt "$content"
    fi
    unset input
    unset output
}

cmd_or_die curl
cmd_or_die jq
verbose=0

# Process command line options
while [ $# -gt 0 ]; do
    case $1 in
        # Two hyphens ends the options parsing
        --)
            shift
            break
            ;;
        # Print help by calling a help() function that you define later
        -h|--help)
            shift
            help
            exit
            ;;
        -v|--verbose)
            shift
            verbose=$((verbose + 1))
            ;;
        -V|--version)
            shift
            out "$program_version"
            ;;
        -i|--input)
            shift
            input="$1"
            shift
            content=$(
                tr '[:space:]' ' ' < "$input" | 
                sed 's/[[:space:]][[:space:]]*/ /g; s/^[[:space:]]*//; s/[[:space:]]*$//;'
            )
            curl_chatgpt_wrapper "$content"
            ;;
        -o|--output)
            shift
            output="$1"
            shift
            ;;        
        -c|--content)
            shift
            content="$1"
            shift
            curl_chatgpt_wrapper "$content"
            ;;        
        --program-command)
            shift
            out "$program_command"
            ;;
        --program-version)
            shift
            out "$program_version"
            ;;
        --program-updated)
            shift
            out "$program_updated"
            ;;
        --program-license)
            shift
            out "$program_license"
            ;;
        --program-website)
            shift
            out "$program_website"
            ;;
        --program-contact)
            shift
            out "$program_contact"
            ;;
        *)
            curl_chatgpt_wrapper "$1"
            shift
            ;;
    esac
done

exit $EX_OK
